### ISSUE TITLE
Context-Broker not recognizing the mapping of same relationship type to multiple objects using python-ngsild-client

### ISSUE THREAD

**Issue by Miracle-lab** [Orange-OpenSource/python-ngsild-client#1]
Dear Python-ngsild Developer,

Please, I am having some constraints in properly passing the same relationship type referenced to multiple object via my context broker.
For example:
entyi = Entity("Vehicle", "A456742")
entyi.rel("isParked", ["OffStreetParking:Downtown4", "OffStreetParking:Downtown5", "OffStreetParking:Downtown6"]).

This example successfully creates the mapping of "isParked" to the multiple object types in my python script. However, when I try to create the entity in my context broker (stellio-context-broker) using "client.create(entyi)", it only recognizes the first entity "OffStreetParking:Downtown4" and ignores the rest objects that are supposed to be created. Attached to this complaint is the image of my script and graph representation in Neo4j since stellio is backed by the Neo4j database. I would appreciate your feedback to overcome this obstacle. Thank you.

![Screenshot from 2022-06-17 11-04-52](https://user-images.githubusercontent.com/66031329/174280677-fad1bbe0-3a62-4b37-a9d0-6269752592d7.png)
![Screenshot from 2022-06-17 11-06-00](https://user-images.githubusercontent.com/66031329/174280684-9ad1d5d9-2487-47d3-bbf8-511d8369acce.png)

**Comment by fbattello** [comment]
Dear Miracle,

Fortunately I'm just working on the multiple-attr support.
ETSI specs have changed since I wrote this part of the library.

I've just committed to github.
May be you can try it directly from github : **pip install git+https://github.com/Orange-OpenSource/python-ngsild-client**

```
from ngsildclient import *

ctx = [
    "http://example.org/ngsi-ld/latest/commonTerms.jsonld",
    "http://example.org/ngsi-ld/latest/vehicle.jsonld",
    "http://example.org/ngsi-ld/latest/parking.jsonld",
    "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.5.jsonld",
]

e = Entity("Vehicle", "A4567", ctx=ctx).prop("brandName", "Mercedes").rel("isParked", ["OffStreetParking:Downtown4", "OffStreetParking:Downtown5", "OffStreetParking:Downtown6"])
```
That way "object" is not repeated alone but the whole relationship is. Hope it could solve your issue.
You could also pass arrays for metadata.
For example :
`e = Entity("Vehicle", "A4567", ctx=ctx).prop("brandName", "Mercedes").rel("isParked", ["OffStreetParking:Downtown4", "OffStreetParking:Downtown5", "OffStreetParking:Downtown6"], datasetid=["source1", "source2", "source3"])`

An alternative way is to create a single relationship and then convert to an array.
```
e = Entity("Vehicle", "A4567", ctx=ctx).prop("brandName", "Mercedes").rel("isParked", "OffStreetParking:Downtown4").rel(Rel.PROVIDED_BY, "Person:Bob", nested=True)
parked = e.arrayify("isParked")
# Update the Python dictionary
parked["object"] = "urn:ngsi-ld:OffStreetParking:Downtown5"
parked["providedBy"]["object"] = "urn:ngsi-ld:Person:Alice"
# Update the entity
e.append("isParked", parked)
```
Let me know if it's better.
It's still work in progress.

Regards

**Comment by Miracle-lab** [comment]
Dear Fabien, 

First of all thank you for the response. Please I want to inform you that the second alternative which you provided worked fine. However, the "datasetid" with "source1, source2, and source3" is not clear to me. I checked the documentation I could not see a detailed description of its use and function. Please can you provide me with some clarification on these concepts. 

Secondly, I tried the first approach you suggested, it was able to create the several mapping to the different object with the same relationship. However, when parsing them to the stellio context broker it generated an error as shown in the image attached below. Thank you.


![Screenshot from 2022-06-20 11-07-34](https://user-images.githubusercontent.com/66031329/174582754-04fb755d-36e3-4731-be4e-27afc019f03e.png)
![Screenshot from 2022-06-20 11-27-15](https://user-images.githubusercontent.com/66031329/174582763-ea5033a9-7e01-4ac6-8196-3640b84191a9.png)
![Screenshot from 2022-06-20 11-27-55](https://user-images.githubusercontent.com/66031329/174582764-a514647d-8de2-4cea-9efe-73f13524f6e9.png)

**Comment by fbattello** [comment]
Dear Miracle,

Depending on features, brokers have different implementations of the [ETSI specifications](https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.05.01_60/gs_CIM009v010501p.pdf).
I tested your code against the Orion broker. It works.
But Stellio complains that there are duplicates.
It happens to work by specifying a distinct datasetId field for each attribute (should be optional according to chapter 4.5.5 - Multiple Attribute Support).
You can try this :
`e.rel("isParked", ["OffStreetParking:Downtown4", "OffStreetParking:Downtown5", "OffStreetParking:Downtown4"], datasetid=["datasource4", "datasource5", "datasource6"])`

**Comment by fbattello** [comment]
Multiple-Relationship support added in v0.1.10.
