### ISSUE TITLE
Query to create an example 

### ISSUE THREAD

**Issue by Neeraj-Nec** [Orange-OpenSource/python-ngsild-client#11]
How to create following example:

{
	"id": "urn:ngsi-ld:vehicle:Abc123",
	"type": "vehicle",
	"@context": ["https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"],
	"room": {
		"type": "Property",
		"value": 23,
		"temp": {
			"type": "Property",
			"value": 40,
			"temp1": {
				"type": "Property",
				"value": 54
			}
		},
		"presure": {
			"type": "Property",
			"value": 40,
			"tempPre": {
				"type": "Property",
				"value": 54
			}
		}
	}
}

**Comment by fbattello** [comment]
One way to build that entity.

```python
from ngsildclient import Entity

e = Entity("Vehicle", "Abc123")
e.prop("room", 23).prop("temp", 40, nested=True).prop("temp1", 54, nested=True)
e.prop("pressure", 40).prop("tempPre", 54, nested=True)
```

**Comment by Neeraj-Nec** [comment]
In my Example presure is the subproperty of "room" but your code is putting the property  "presure"  outside room

**Comment by Neeraj-Nec** [comment]
I think you should check update function for all ngsild cases

**Comment by Neeraj-Nec** [comment]
You should check your update function for all ngsild cases
