### ISSUE TITLE
Request: Support options for Batch Operations /upsert and /update

### ISSUE THREAD

**Issue by Blobonat** [Orange-OpenSource/python-ngsild-client#5]
Hi,

the NGSI-LD spec defines several query parameters that can be used with the `entityOperations/upsert` and `entityOperations/update` endpoints, e.g. `entityOperations/upsert?options=update`. 

It would be nice to have support for these options within the client.

**Comment by fbattello** [comment]
Added in v0.5.0 and published to PyPI.

- For batch upsert, the default `replace` behaviour is made explicit, always forced in the url params like this : `?options=replace`
The `upsert()` method takes a new argument to switch to the `update` mode.
```python
def upsert(self, *entities, update: bool = False)`
```

- For batch update, the `update()` method takes a new `overwrite` boolean argument whose default value is `True`.
Meaning that setting it to `False` corresponds to `?options=noOverwrite` of the ETSI specification.
```python
def update(self, *entities, overwrite: bool = True)`
```
